services:
  redis:
    image: redis:7.2-alpine
    container_name: my_redis_cache
    ports:
      - "6370:6379"
  
  server:
    build: ./server
    ports:
      - "4456:4456"
    environment:
      - PPORT=3344
      - REDIS_PORT=6379
      - REDIS_HOST=my_redis_cache  # ✅ Fixed hostname
    depends_on:
      - redis  # ✅ Wait for Redis

  app:
    build: ./app
    ports:
      - "6655:5173"
    environment:
      - VITE_HOST=http://server
      - VITE_SERVER_PORT=4456
    
  networks:
  default:
    driver: bridge
