services:
  redis:
    image: redis:7.2-alpine
    container_name: my_redis_cache
    ports:
      - "6370:6379"
  
  server:
    build: ./server
    ports:
      - "4456:4456"
    environment:
      - PPORT=4456
      - REDIS_PORT=6379
      - REDIS_HOST=my_redis_cache
    depends_on:
      - redis

  app:
    build: ./app
    ports:
      - "6655:5173"
    environment:
      - VITE_HOST=http://server:4456
